/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#a2f31f",
        "on-tertiary-container": "#365700",
        "surface-container-low": "#131313",
        "on-secondary-fixed-variant": "#005e64",
        "secondary-fixed": "#00eefc",
        "error-container": "#b92902",
        "on-secondary": "#005359",
        "primary-dim": "#e4006c",
        "surface-container-high": "#20201f",
        "on-primary-container": "#4c0020",
        "secondary-fixed-dim": "#00deec",
        "on-background": "#ffffff",
        "inverse-surface": "#fcf9f8",
        error: "#ff7351",
        "surface-container-lowest": "#000000",
        primary: "#ff8aa9",
        "on-primary": "#62002b",
        "inverse-on-surface": "#565555",
        "surface-dim": "#0e0e0e",
        "primary-fixed": "#ff719b",
        "on-surface": "#ffffff",
        "surface-container-highest": "#262626",
        "primary-fixed-dim": "#ff528c",
        "on-error-container": "#ffd2c8",
        "on-tertiary": "#3d6100",
        "primary-container": "#ff719b",
        "on-surface-variant": "#adaaaa",
        "secondary-dim": "#00deec",
        background: "#0e0e0e",
        "inverse-primary": "#bc0058",
        "tertiary-container": "#a2f31f",
        "on-secondary-fixed": "#003f43",
        "on-error": "#450900",
        "outline-variant": "#484847",
        "on-primary-fixed": "#000000",
        outline: "#767575",
        "error-dim": "#d53d18",
        "surface-tint": "#ff8aa9",
        "surface-bright": "#2c2c2c",
        "tertiary-fixed-dim": "#95e400",
        "on-secondary-container": "#e3fdff",
        "on-tertiary-fixed-variant": "#3d6200",
        "on-primary-fixed-variant": "#5e0028",
        "on-tertiary-fixed": "#294300",
        "tertiary-dim": "#95e400",
        "surface-container": "#1a1a1a",
        surface: "#0e0e0e",
        secondary: "#00eefc",
        "surface-variant": "#262626",
        tertiary: "#bcff5f",
        "secondary-container": "#006970",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
